//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.WindowApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="StudentService", ConfigurationName="ServiceReference1.IStudentService")]
    public interface IStudentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="StudentService/IStudentService/GetUpperCaseText", ReplyAction="StudentService/IStudentService/GetUpperCaseTextResponse")]
        string GetUpperCaseText(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="StudentService/IStudentService/GetUpperCaseText", ReplyAction="StudentService/IStudentService/GetUpperCaseTextResponse")]
        System.Threading.Tasks.Task<string> GetUpperCaseTextAsync(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentServiceChannel : Client.WindowApp.ServiceReference1.IStudentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServiceClient : System.ServiceModel.ClientBase<Client.WindowApp.ServiceReference1.IStudentService>, Client.WindowApp.ServiceReference1.IStudentService {
        
        public StudentServiceClient() {
        }
        
        public StudentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetUpperCaseText(string text) {
            return base.Channel.GetUpperCaseText(text);
        }
        
        public System.Threading.Tasks.Task<string> GetUpperCaseTextAsync(string text) {
            return base.Channel.GetUpperCaseTextAsync(text);
        }
    }
}
